version: '3'
services:
  20q-sql:
    container_name: '20q-sql'
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: 'Yes'
      SA_PASSWORD: '20QDevDatabasePassword'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
      
  20q-web:
    container_name: '20q-web'
    depends_on:
      - '20q-sql'
    build:
      context: .
    image: docker.pkg.github.com/jordankasper11/twenty-questions/20q-web
    volumes:
      - C:\Projects\TwentyQuestions\Storage\avatars:/storage
    environment:
      Database__ConnectionString: 'Server=20q-sql;Database=20Q;User ID=sa;Password=20QDevDatabasePassword;'
      Authentication__SecurityKey: '20QDevSecurityKey'
      Paths__Avatars: 'C:\Projects\TwentyQuestions\Storage\avatars'
    ports:
      - '80:80'