name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      env:
        DOCKER_USER: $GITHUB_ACTOR
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login https://docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build . --file Dockerfile --tag docker.pkg.github.com/jordankasper11/twenty-questions/20q-web:latest
        docker push docker.pkg.github.com/jordankasper11/twenty-questions/20q-web:latest